server:
  port: 1000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liquibase?serverTimezone=UTC
    username: root
    password: root

  liquibase:
    enabled: false
    change-log: classpath:db_changelog/changelog-master.yaml

